hydra: 
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    # dir: outputs/${data.name}/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}
    # dir: outputs/${dataset.name}/${.model_name}/${experiment}/${experiment_id}
    dir: ${model_dirpath}

defaults:
  - io_dirpaths
  - _self_
  - dataset: middlebury
  # - dataset: nyuv2_min
  # - dataset: nyuv2
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

train_dataset: nyuv2_64x64x1024_80ps

## Peng et al., 2020 --> Full trained model NO gradient decay
# model_dirpath: outputs/${.model_name}/debug_nyuv2/2022-04-19_205134

# ## Peng et al., 2020 --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_original
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-20_185832
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0281

# ## Peng et al., 2020 (Plain Deep Boosting w/out NL) --> Full trained model with gradient decay
# model_name: DDFN_C64B10
# model_dirpath: outputs/${.train_dataset}/DDFN_C64B10/debug/2022-04-25_192521
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0287

# ## 3D DB Non-Local Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_Depth2Depth
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-22_134732
# ckpt_id: epoch=05-step=19045-avgvalrmse=0.0363

# ## 3D DB Plain Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN_C64B10_Depth2Depth
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-02_085659
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0357

# ## 3D DB Plain Depth2Depth Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_Depth2Depth
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/loss-kldiv_tv-0.0/2022-05-07_171658
# ckpt_id: epoch=08-step=28569-avgvalrmse=0.0263

# ## K=16 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-11_070443
# ckpt_id: epoch=09-step=33762-avgvalrmse=0.0225 # ~0.034

# ## K=16 TruncFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-14_175011
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0213

## K=16 TruncFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
model_name: DDFN_C64B10_CSPH1D/k16_TruncFourier/loss-kldiv_tv-0.0
model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-19_142207
ckpt_id: epoch=08-step=31166-avgvalrmse=0.0180


# ## K=16 CoarseHist 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_CoarseHist/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-15_103103
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0257

# ## K=64 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-18_050753
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0183 # ~0.034

# ## K=64 TruncFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-17_121426
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0184 # ~0.034

# ## K=64 CoarseHist 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_CoarseHist/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-17_224020
# ckpt_id: epoch=09-step=32898-avgvalrmse=0.0198 # ~0.034


# ## 3D DB Plain CSPH1D Model (1e-5 TV) -- With seed 1234 and 0th harmonic
# model_name: DDFN_C64B10_CSPH1D/k16_HybridGrayFourier/loss-kldiv_tv-1e-05
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-13_203112
# ckpt_id: epoch=06-step=22509-avgvalrmse=0.0308


# ## Compressive --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_Compressive
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-23_132059
# ckpt_id: epoch=06-step=23373-avgvalrmse=0.0320

# ## CompressiveWithBias --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_CompressiveWithBias
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-24_142932
# ckpt_id: epoch=05-step=18180-avgvalrmse=0.0323


# ## Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth/B-12_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-27_103314
# ckpt_id: epoch=29-step=103022-avgvalrmse=0.0306 # use last one

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-27_104532
# ckpt_id: epoch=29-step=101292-avgvalrmse=0.0280 # use last one

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8/loss-L1_tv-0.001
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-03_183044
# ckpt_id: epoch=24-step=86572-avgvalrmse=0.0470 # use last one

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8/loss-L1_tv-0.0001
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-03_183002
# ckpt_id: epoch=24-step=86572-avgvalrmse=0.0286

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8/loss-L1_tv-3e-05
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-03_185303
# ckpt_id: epoch=25-step=90035-avgvalrmse=0.0285 # use last one

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8/loss-L1_tv-1e-10
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-03_183128
# ckpt_id: epoch=26-step=92633-avgvalrmse=0.0279 # use last one

# ## 01Inputs Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-24_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-04-28_163253
# ckpt_id: epoch=26-step=91768-avgvalrmse=0.0267

# ## 01Inputs Depth2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-16_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-01_172344
# ckpt_id: epoch=46-step=161893-avgvalrmse=0.0240 #0.075
# # ckpt_id: epoch=11-step=39823-avgvalrmse=0.0279 # 0.097
# # ckpt_id: epoch=12-step=45016-avgvalrmse=0.0279 # 0.1
# # ckpt_id: epoch=13-step=47614-avgvalrmse=0.0294 # 0.14
# # ckpt_id: epoch=15-step=52810-avgvalrmse=0.0291 # 0.045
# # ckpt_id: epoch=15-step=53675-avgvalrmse=0.0280 # 0.086
# # ckpt_id: epoch=16-step=57138-avgvalrmse=0.0279 # 0.099
# # ckpt_id: epoch=18-step=65794-avgvalrmse=0.0263 # 0.10
# # ckpt_id: epoch=20-step=72720-avgvalrmse=0.0273 #0.088
# # ckpt_id: epoch=21-step=75318-avgvalrmse=0.0255 #0.1
# # ckpt_id: epoch=23-step=82244-avgvalrmse=0.0260 #0.1
# # ckpt_id: epoch=24-step=83977-avgvalrmse=0.0283 #0.23
# # ckpt_id: epoch=25-step=89170-avgvalrmse=0.0255 #0.086
# # ckpt_id: epoch=27-step=95231-avgvalrmse=0.0266 #0.1
# # ckpt_id: epoch=29-step=103022-avgvalrmse=0.0258 #0.09
# # ckpt_id: epoch=31-step=109083-avgvalrmse=0.0256 # 0.078
# # ckpt_id: epoch=37-step=128996-avgvalrmse=0.0258 # 0.09
# # ckpt_id: epoch=42-step=147176-avgvalrmse=0.0259 # 0.063

# ## 01Inputs Depth2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-16_MS-8/loss-L1_tv-1e-05
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-04_134615
# ckpt_id: null

# ## 01Inputs Depth2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-16_MS-8/loss-L1_tv-3e-05
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-04_133635
# ckpt_id: null

# ## Phasor2Depth LARGE Model (16 freqs) --> Full trained model with gradient decay
# model_name: DDFN2D_Phasor2Depth/B-16_MS-8/loss-L1_tv-1e-05
# model_dirpath: outputs/${.train_dataset}/test/${.model_name}/2022-05-05_122615
# ckpt_id: epoch=30-step=53692-avgvalrmse=0.0279 # 0.069, 

# ## Phasor2Depth LARGE Model (ALL freqs) --> Full trained model with gradient decay
# model_name: DDFN2D_Phasor2Depth/B-16_MS-8/loss-L1_tv-1e-05
# model_dirpath: outputs/${.train_dataset}/test/${.model_name}/2022-05-14_133347
# ckpt_id: epoch=29-step=102158-avgvalrmse=0.0287 # 0.104, 

# ## Phasor2Depth LARGE Model (ALL freqs) --> Full trained model with gradient decay
# model_name: DDFN2D_Phasor2Depth/B-16_MS-8/loss-L1_tv-0.0/
# model_dirpath: outputs/${.train_dataset}/test/${.model_name}/2022-05-12_145104
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0291 # 0.104, 

# ## Depth2Depth2Hist Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth2Hist_01Inputs/B-12_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-02_214727
# ckpt_id: epoch=42-step=148041-avgvalrmse=0.0281


params:
  gpu_num: 1
  batch_size: 1
  num_workers: 8
  cuda: true
  noise_idx: null
  test_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.test_datalist_fname}


