hydra: 
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    # dir: outputs/${data.name}/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}
    # dir: outputs/${dataset.name}/${.model_name}/${experiment}/${experiment_id}
    dir: ${model_dirpath}

defaults:
  - io_dirpaths
  - _self_
  - dataset: middlebury
  # - dataset: lindell2018_linospad
  # - dataset: lindell2018_linospad_min
  # - dataset: nyuv2_min
  # - dataset: nyuv2
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

train_dataset: nyuv2_64x64x1024_80ps

##########################################
## Peng et al., 2020 Baselines and Modified 

# ## Peng et al., 2020 --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_original
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-20_185832
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0281

# ## Peng et al., 2020 (Plain Deep Boosting w/out NL) --> Full trained model with gradient decay
# model_name: DDFN_C64B10
# model_dirpath: outputs/${.train_dataset}/debug/DDFN_C64B10/2022-04-25_192521
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0287 # 0.0180 | 0.0177 | 0.0203

# ## 3D DB Plain Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN_C64B10_Depth2Depth
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/loss-kldiv_tv-1e-5/2022-05-02_085659
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0357 # | 0.0239 | 0.0276

# ## 3D DB Plain Depth2Depth Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_Depth2Depth
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/loss-kldiv_tv-0.0/2022-05-07_171658
# ckpt_id: epoch=08-step=28569-avgvalrmse=0.0263 # | 0.0292


##########################################
## 1D CSPH with ZNCC Upsampling

#### K = 8 (compression = 128x)

# ## K=8 FourierGray 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k8_HybridFourierGray/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-26_084337
# ckpt_id: epoch=17-step=62333-avgvalrmse=0.0219 # 0.0403 | 0.0356

# ## K=8 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k8_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-27_181604
# ckpt_id: epoch=19-step=67528-avgvalrmse=0.0201 # 0.0442 | 0.0320 | 

#### K = 16 (compression = 64x)

# ## K=16 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV, LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-20_194518
# ckpt_id: epoch=19-step=69259-avgvalrmse=0.0184 # 0.029 | 0.0203

# ## K=16 TruncFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-19_142207
# ckpt_id: epoch=19-step=69259-avgvalrmse=0.0170 # 0.0346

# ## K=16 CoarseHist 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_CoarseHist/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-15_103103
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0257 #

#### K = 32 (compression = 32x)

# ## K=32 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k32_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-20_194601
# ckpt_id: epoch=19-step=69259-avgvalrmse=0.0152 # 0.0208 | 

# ## K=32 TruncFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k32_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-26_075946
# ckpt_id: epoch=18-step=64065-avgvalrmse=0.0150 # 0.0199

#### K = 64 (compression = 16x)

# ## K=64 HybridGrayFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_HybridGrayFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-18_050753
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0183 # 0.0179

# ## K=64 TruncFourier 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-17_121426
# ckpt_id: epoch=09-step=34629-avgvalrmse=0.0184 # 0.0177

# ## K=64 CoarseHist 3D DB Plain CSPH1D Model (No TV) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k64_CoarseHist/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/debug/${.model_name}/2022-05-17_224020
# ckpt_id: epoch=09-step=32898-avgvalrmse=0.0198 # ~0.0413


##########################################
## 3D CSPH with Pseudo-inverse Upsampling

#### codes=(64x4x4) tblock_init=Rand encoding_type=full

# ## 32x compression --> mt=16, mr,mc=8, k=32
# model_name: DDFN_C64B10_CSPH3Dv1/k32_down4_Mt16_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-16_122403
# ckpt_id: epoch=29-step=102158-avgvalrmse=0.0146.ckpt #  0.01748 |  

# ## 64x compression
# model_name: DDFN_C64B10_CSPH3Dv1/k16_down4_Mt16_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-16_142109
# ckpt_id: epoch=24-step=84843-avgvalrmse=0.0169.ckpt # 0.02163 | 

#### codes=(128x4x4) tblock_init=Rand encoding_type=full

# ## 128x compression
# model_name: DDFN_C64B10_CSPH3Dv1/k16_down4_Mt8_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-13_193650
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0189.ckpt # 0.0248 | 

# ## 256x compression
# model_name: DDFN_C64B10_CSPH3Dv1/k8_down4_Mt8_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-13_171326
# ckpt_id: epoch=27-step=96963-avgvalrmse=0.0220.ckpt # 0.0319 | 

#### codes=(1024x4x4) tblock_init=Rand encoding_type=full

## 32x compression (K=512 1024x4x4)
model_name: DDFN_C64B10_CSPH3D/k512_down4_Mt1_Rand-optCt=True-optC=True_full_norm-none/loss-kldiv_tv-0.0
experiment_name: test_csph3d
model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-10_162141
ckpt_id: epoch=28-step=98695-avgvalrmse=0.0171.ckpt # 0.0191 | 

# ## 64x compression (K=256 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k256_down4_Mt1_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-05_141013
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0175 # 0.0206 |

# ## 128x compression (K=128 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k128_down4_Mt1_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-31_145411
# ckpt_id: epoch=26-step=91769-avgvalrmse=0.0180.ckpt # 0.0240 |

# ## 256x compression (K=64 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k64_down4_Mt1_Rand-optCt=True-optC=True_full/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-07-25_212205
# ckpt_id: epoch=28-step=98695-avgvalrmse=0.0193.ckpt # 0.0254 |


#### codes=(1024x4x4) tblock_init=Rand encoding_type=separable

# ## 32x compression (K=512 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k512_down4_Mt1_Rand-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-11_145814
# ckpt_id: epoch=28-step=100426-avgvalrmse=0.0143.ckpt # 0.0206 | 

# ## 64x compression (K=256 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k256_down4_Mt1_Rand-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-11_145814
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0150.ckpt # 0.0181 |

# ## 128x compression (K=128 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k128_down4_Mt1_Rand-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-11_145813
# ckpt_id: epoch=29-step=102158-avgvalrmse=0.0170.ckpt # 0.0335 |

# ## 256x compression (K=64 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k64_down4_Mt1_Rand-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-11_145814
# ckpt_id: epoch=27-step=95232-avgvalrmse=0.0185.ckpt # 0.0313 |

#### codes=(1024x4x4) tblock_init=HybridGrayFourier encoding_type=separable

# ## 32x compression (K=512 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k512_down4_Mt1_HybridGrayFourier-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-10_013956
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0164.ckpt # 0.0163 | 

# ## 64x compression (K=256 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k256_down4_Mt1_HybridGrayFourier-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-10_014005
# ckpt_id: epoch=29-step=103889-avgvalrmse=0.0170.ckpt # 0.01849 |

# ## 128x compression (K=128 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k128_down4_Mt1_HybridGrayFourier-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-10_014115
# ckpt_id: epoch=26-step=91769-avgvalrmse=0.0176.ckpt # 0.0195 |

# ## 256x compression (K=64 1024x4x4)
# model_name: DDFN_C64B10_CSPH3Dv1/k64_down4_Mt1_HybridGrayFourier-optCt=True-optC=True_separable/loss-kldiv_tv-0.0
# experiment_name: test_csph3d
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/${.experiment_name}/${.model_name}/2022-08-10_014223
# ckpt_id: epoch=25-step=90037-avgvalrmse=0.0187.ckpt # 0.0252 |

params:
  gpu_num: 1
  batch_size: 1
  num_workers: 4
  cuda: true
  noise_idx: null
  test_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.test_datalist_fname}


