hydra: 
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    # dir: outputs/${data.name}/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}
    # dir: outputs/${dataset.name}/${.model_name}/${experiment}/${experiment_id}
    dir: ${model_dirpath}

defaults:
  - io_dirpaths
  - _self_
  - dataset: middlebury
  # - dataset: nyuv2_min
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

train_dataset: nyuv2_64x64x1024_80ps

## Peng et al., 2020 --> Full trained model NO gradient decay
# model_dirpath: outputs/${.model_name}/debug_nyuv2/2022-04-19_205134

# ## Peng et al., 2020 --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_original
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-20_185832
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0281

# ## Peng et al., 2020 (Plain Deep Boosting w/out NL) --> Full trained model with gradient decay
# model_name: DDFN_C64B10
# model_dirpath: outputs/${.train_dataset}/DDFN_C64B10/debug/2022-04-25_192521
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0287

# ## 3D DB Non-Local Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_Depth2Depth
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-22_134732
# ckpt_id: epoch=05-step=19045-avgvalrmse=0.0363

# ## 3D DB Plain Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN_C64B10_Depth2Depth
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-02_085659
# ckpt_id: epoch=05-step=19910-avgvalrmse=0.0357

# ## Compressive --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_Compressive
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-23_132059
# ckpt_id: epoch=06-step=23373-avgvalrmse=0.0320

# ## CompressiveWithBias --> Full trained model with gradient decay
# model_name: DDFN_C64B10_NL_CompressiveWithBias
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-24_142932
# ckpt_id: epoch=05-step=18180-avgvalrmse=0.0323


# ## Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth/B-12_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-27_103314
# ckpt_id: epoch=29-step=103022-avgvalrmse=0.0306 # use last one

## Depth2Depth Model --> Full trained model with gradient decay
model_name: DDFN2D_Depth2Depth_01Inputs/B-12_MS-8
model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/debug/2022-04-27_104532
ckpt_id: epoch=29-step=101292-avgvalrmse=0.0280 # use last one

# ## Depth2Depth Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-24_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-04-28_163253
# ckpt_id: epoch=26-step=91768-avgvalrmse=0.0267

# ## Depth2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth_01Inputs/B-16_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-01_172344
# ckpt_id: epoch=46-step=161893-avgvalrmse=0.0240
# # ckpt_id: epoch=21-step=73588-avgvalrmse=0.0253 
# # ckpt_id: epoch=18-step=64929-avgvalrmse=0.0290
# # ckpt_id: epoch=11-step=38958-avgvalrmse=0.0306
# # ckpt_id: epoch=16-step=58003-avgvalrmse=0.0270

# ## Depth2Depth2Hist Model --> Full trained model with gradient decay
# model_name: DDFN2D_Depth2Depth2Hist_01Inputs/B-12_MS-8
# model_dirpath: outputs/${.train_dataset}/debug/${.model_name}/2022-05-02_214727
# ckpt_id: epoch=42-step=148041-avgvalrmse=0.0281


params:
  gpu_num: 1
  cuda: true
  batch_size: 1
  noise_idx: null
  test_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.test_datalist_fname}


