hydra: 
  run:
    dir: ${model_dirpath}

#### Useful variables to have
# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# # ## 01Inputs Depth2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Phasor2Depth/B-16_MS-8/loss-L1_tv-0.0
# model_dirpath: outputs/${dataset.name}/${experiment}/${model_name}/2022-05-12_141759
# ckpt_id: epoch=00-step=3463-end-of-epoch

# # ## 01Inputs Phasor2Depth LARGE Model --> Full trained model with gradient decay
# model_name: DDFN2D_Phasor2Depth/B-16_MS-8/loss-L1_tv-1e-05
# model_dirpath: outputs/${dataset.name}/${experiment}/${model_name}/2022-05-18_042156
# ckpt_id: epoch=09-step=20782-end-of-epoch


# ## K=16 TruncFourier 3D DB Plain CSPH1D Model (No TV | LR=1e-3) --> Full trained model with gradient decay
# model_name: DDFN_C64B10_CSPH1D/k16_TruncFourier/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-05-19_142207
# ckpt_id: epoch=09-step=34630-end-of-epoch

# # ## 64x compression K=256 CSPH Separable 4x4x1024 (learned spatial, learned up) TruncFourier (No TV) 
# model_name: DDFN_C64B10_CSPH/k256_down4_Mt1_TruncFourier-opt-True_separable/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-06-22_130057
# # ckpt_id: epoch=19-step=67528-avgvalrmse=0.0194 # 0.0243 | 0.0223
# ckpt_id: epoch=19-step=69260-end-of-epoch

# ## 128x compression K=128 CSPH Separable 4x4x1024 (learned spatial, learned up) TruncFourier (No TV) 
# model_name: DDFN_C64B10_CSPH/k128_down4_Mt1_TruncFourier-opt-True_separable/loss-kldiv_tv-0.0
# model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph/${.model_name}/2022-06-18_203447
# # ckpt_id: epoch=17-step=62333-avgvalrmse=0.0197 # 0.0247 | 0.0227
# ckpt_id: epoch=19-step=69260-end-of-epoch.ckpt


## 256x compression K=8 CSPH3D Full 4x4x1024 Rand (No TV) 
model_name: DDFN_C64B10_CSPH3D/k8_down4_Mt8_Rand-opt-True_full/loss-kldiv_tv-0.0
model_dirpath: outputs/nyuv2_64x64x1024_80ps/test_csph3d/${.model_name}/2022-07-13_171326
ckpt_id: epoch=06-step=24241-end-of-epoch.ckpt

defaults:
  - _self_
  - io_dirpaths
  - train_params: debug
  - dataset: nyuv2
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# Global configurations shared between different modules
# NOTE: only used for some of the above
experiment: test

# Random seed to use
random_seed: 1234

params:
  train_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.train_datalist_fname}
  val_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.val_datalist_fname}

