hydra: 
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    # dir: outputs/${data.name}/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}
    # dir: outputs/${dataset.name}/${model.model_name}/${experiment}/${now:%Y-%m-%d_%H%M%S}
    dir: outputs/${dataset.name}/${experiment}/${model.model_name}/${now:%Y-%m-%d_%H%M%S}

#### Useful variables to have
# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - io_dirpaths
  - train_params: debug
  - dataset: nyuv2
  # - dataset: nyuv2_min_overfit
  # - model: DDFN_C64B10_NL
  # - model: DDFN_C64B10_NL_Depth2Depth
  # - model: DDFN_C64B10_NL_Compressive
  # - model: DDFN_C64B10
  # - model: DDFN2D_Depth2Depth
  - model: DDFN2D_Depth2Depth_01Inputs
  # - model: DDFN2D_Depth2Hist_01Inputs
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# Global configurations shared between different modules
experiment: debug

# Random seed to use
random_seed: 1234

params:
  train_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.train_datalist_fname}
  val_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.val_datalist_fname}

