#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=15
#SBATCH --mem=60000
#SBATCH --time=48:0:0
###SBATCH --nodelist=euler141
###SBATCH --exclude=euler09
#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH --job-name=pensim

module load matlab/r2021b

# matlab -nodisplay -nosplash -nodesktop -r 'SimulateSUNRGBDMeasurements(3,6);quit;'

#START=$1
#TOTAL=$2
#EACH=$3
#SPLITS=$TOTAL/$EACH
#for (( i = 0; i < $SPLITS; i++ ))
#do
#	BEGIN=$(($i*$EACH+$START))
#	echo $BEGIN
#	matlab -nodisplay -nosplash -nodesktop -r 'SimulateSUNRGBDMeasurements('$BEGIN','$(($BEGIN+$EACH))');quit;' &
#	sleep 60
#done

#wait

matlab -nodisplay -nosplash -nodesktop -r 'SimulateSUNRGBDMeasurements('$1','$2');quit;'

