
overfit_batches: false
disable_rand_crop: false
gpu_num: 1
cuda: true
batch_size: 4
workers: 4
epoch: 10
lri: 1.0e-4
# lri: 1.0e-3
lr_decay_gamma: 0.9
p_tv: 1.0e-5
noise_idx: 1
crop_patch_size: 32
train_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.train_datalist_fname}
val_datalist_fpath: ${io_dirpaths.datalists_dirpath}/${dataset.val_datalist_fname}
